# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 22, host: 22022
  config.vm.network "forwarded_port", guest: 80, host: 22080
  config.vm.network "forwarded_port", guest: 443, host: 22443
  config.vm.network "forwarded_port", guest: 22306, host: 3306

  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end


  # Provisioning configuration for Ansible.
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end
end